### ISSUE TITLE
[PE-D] Potential Misleading Edit Command Error Message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-1/tp#164]
This might be a very minor bug, perhaps a more useful error message is better. This can be misleading as the user might think there is a problem with the student id, but it's not. Just that it provides field that is not supported by the `edit` command (Editing event name)

![image.png](https://raw.githubusercontent.com/DystoriaX/ped/main/files/9ac5f5fd-c2f4-42ff-81db-1d21f6774191.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: DystoriaX/ped#3

**Comment by wowsiddanth** [comment]
Thank you for reporting this bug :)
