### ISSUE TITLE
[PE-D] Good Job!!

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-1/tp#167]
![image.png](https://raw.githubusercontent.com/choonyongchan/ped/main/files/4cd0fdd0-97f2-4e87-9020-eccfc059a731.png)

(since it's just pe dry run i'll say it) Jiayouz!! All the best for this semester Team T11!!

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: choonyongchan/ped#8

**Comment by wowsiddanth** [comment]
Thank you for the kind words, you too man.

**Comment by Joel-Sung** [comment]
Thanks
