### ISSUE TITLE
Difference in behaviour of UI Buttons

### ISSUE THREAD

**Issue by TLChicken** [AY2122S1-CS2103T-T11-1/tp#174]
![image](https://user-images.githubusercontent.com/57408415/139526008-04e619f2-67b6-4004-bf3d-7525adcced46.png)

 In Dark mode when I hold down the button the borders will light up for all the buttons in the top row and the buttons will move, but in Light mode when I hold down the button the inside lights up only for the buttons with text, there is no feedback for the change theme button

**Comment by wowsiddanth** [comment]
Unimplemented feature.
