### ISSUE TITLE
[PE-D] Add Profile Picture: Adding Recommended Picture Size

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-1/tp#183]
Regarding adding profile picture, it could be better if you also provide the recommended size of the picture. It helps the user to understand and crop the picture as necessary so that it can be previewed better in the app.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: DystoriaX/ped#10

**Comment by wowsiddanth** [comment]
Fixed.
